### ISSUE TITLE
GregTech tools will break with Unbreakable tag when crafting with them

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#11] opened 2024-01-02 15:02 UTC
new issue unbreackable upgrde did't work at GT Tools if shift click still will breack gt tools
onther item look fine some time it did't breack some time it breack zzzz

**Comment by MindBrain27** [comment] 2024-01-02 15:30
This is for consuming a Netherite Block correct? Are you saying it did consume the block and added the unbreakable tag but it still takes durability damage? If so was it using the tool in world or using to craft?

**Comment by akasia** [comment] 2024-01-02 15:59
yes i has unbreakable tag and it breack when using to craft

**Comment by MindBrain27** [comment] 2024-01-02 16:01
I haven't tested tools with crafting yet so that may not be working as intended but they should work as tools in world, I will mess around with this tonight.

**Comment by MindBrain27** [comment] 2024-01-02 18:50
What tool were you using and what were you crafting?

I made an unbreakable Diamond Hammer and I can shift click craft without it taking any durability damage, same as unbreakable Wire Cutters seem to work fine.

Maybe some tools are not working properly.

**Comment by akasia** [comment] 2024-01-02 21:38
i using iron tools set all still can breack using ae terminal it did;t breack  at 1st stack but breack 2nd stack and it didt take durability damage just when missing at 2nd stack

**Comment by MindBrain27** [comment] 2024-01-02 22:08
Ok I see now, working on that to see if I can fix, they say unbreakable but still count damage in the NBT tags and break when crafting.

**Comment by MindBrain27** [comment] 2024-01-02 22:38
Can confirm it works fine for in world interactions for Wire Cutters on Cables and Hammers on Cobblestone and such, but crafting does use a hidden durability that breaks after so many uses, not sure if I can do anything about that as of now.

**Comment by MindBrain27** [comment] 2024-01-07 21:07
This seems to be fixed with next GT update actually!

**Comment by akasia** [comment] 2024-01-08 01:22
nice~even that i just pass tool crafting stage but still very usefull for some simple recipe crafting don't need assemble that slow at eary stage

**Comment by MindBrain27** [comment] 2024-01-08 21:24
Fixed with new GT tools update.

**Closed as completed by MindBrain27** 2024-01-08 21:24 UTC
Labels: bug, next update
